services:
  - type: web
    name: ottonomi-server
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI_ATLAS
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: UPLOAD_DIR
        value: uploads